apiVersion: v1
kind: Service
metadata:
 name: node-exporter
 namespace: ahmad-monitoring
 labels:
   app: node-exporter
spec:
 type: ClusterIP
 selector:
   app: node-exporter
 ports:
   - name: metrics
     port: 19100
     targetPort: 19100
