apiVersion: v1
kind: ServiceAccount
metadata:
 name: node-exporter
 namespace: ahmad-monitoring


---
apiVersion: apps/v1
kind: DaemonSet
metadata:
 name: node-exporter
 namespace: ahmad-monitoring
 labels:
   app: node-exporter
spec:
 selector:
   matchLabels:
     app: node-exporter
 template:
   metadata:
     labels:
       app: node-exporter
   spec:
     serviceAccountName: node-exporter
     hostNetwork: true
     hostPID: true
     containers:
       - name: node-exporter
         image: prom/node-exporter:v1.8.1
         args:
           - --path.procfs=/host/proc
           - --path.sysfs=/host/sys
           - --path.rootfs=/host/root
           - --collector.textfile.directory=/var/lib/node_exporter/textfile_collector
         ports:
           - name: metrics
             containerPort: 9100
         volumeMounts:
           - name: proc
             mountPath: /host/proc
             readOnly: true
           - name: sys
             mountPath: /host/sys
             readOnly: true
           - name: root
             mountPath: /host/root
             readOnly: true
           - name: textfile
             mountPath: /var/lib/node_exporter/textfile_collector
     volumes:
       - name: proc
         hostPath:
           path: /proc
       - name: sys
         hostPath:
           path: /sys
       - name: root
         hostPath:
           path: /
       - name: textfile
         hostPath:
           path: /var/lib/node_exporter/textfile_collector
           type: DirectoryOrCreate
