apiVersion: v1
kind: ServiceAccount
metadata:
  name: trivy-cve-exporter
  namespace: ahmad-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: trivy-cve-exporter
rules:
  - apiGroups: ["aquasecurity.github.io"]
    resources:
      - vulnerabilityreports
      - clustervulnerabilityreports
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods", "namespaces"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: trivy-cve-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: trivy-cve-exporter
subjects:
  - kind: ServiceAccount
    name: trivy-cve-exporter
    namespace: ahmad-monitoring
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trivy-cve-exporter
  namespace: ahmad-monitoring
data:
  exporter.py: |
    from flask import Flask, Response, jsonify
    from kubernetes import client, config
    from prometheus_client import Gauge, CollectorRegistry, generate_latest, CONTENT_TYPE_LATEST

    app = Flask(__name__)

    # --------------------
    # Kubernetes helpers
    # --------------------
    def load_kube():
        try:
            config.load_incluster_config()
        except Exception:
            config.load_kube_config()

    def list_reports():
        api = client.CustomObjectsApi()
        group = "aquasecurity.github.io"
        version = "v1alpha1"

        reports = []
        reports += api.list_cluster_custom_object(group, version, "vulnerabilityreports").get("items", [])
        reports += api.list_cluster_custom_object(group, version, "clustervulnerabilityreports").get("items", [])
        return reports

    def extract_image(spec):
        art = spec.get("artifact", {})
        return {
            "repository": art.get("repository", "unknown"),
            "tag": art.get("tag", "latest"),
        }

    def extract_pod(meta):
        labels = meta.get("labels", {})
        return labels.get("trivy-operator.resource.name", "image-scan")

    # --------------------
    # PROMETHEUS METRICS
    # --------------------
    @app.route("/metrics")
    def metrics():
        load_kube()
        reg = CollectorRegistry()

        g = Gauge(
            "trivy_vulnerabilities_total",
            "Trivy vulnerabilities by namespace and severity",
            ["namespace", "severity"],
            registry=reg,
        )

        for r in list_reports():
            ns = r.get("metadata", {}).get("namespace", "cluster")
            for v in r.get("report", {}).get("vulnerabilities", []):
                g.labels(ns, v.get("severity", "UNKNOWN")).inc()

        return Response(generate_latest(reg), mimetype=CONTENT_TYPE_LATEST)

    # --------------------
    # FULL CVE INVENTORY
    # --------------------
    @app.route("/cves")
    def cves():
        load_kube()
        rows = []

        for r in list_reports():
            meta = r.get("metadata", {})
            spec = r.get("spec", {})
            ns = meta.get("namespace", "cluster")
            pod = extract_pod(meta)
            image = extract_image(spec)

            for v in r.get("report", {}).get("vulnerabilities", []):
                rows.append({
                    "namespace": ns,
                    "pod": pod,
                    "image": f'{image["repository"]}:{image["tag"]}',
                    "vuln_id": v.get("vulnerabilityID"),
                    "severity": v.get("severity"),
                    "score": v.get("score"),
                    "package": v.get("resource"),
                    "installed_version": v.get("installedVersion"),
                    "fixed_version": v.get("fixedVersion"),
                    "title": v.get("title"),
                    "primary_link": v.get("primaryLink"),
                    "published_date": v.get("publishedDate"),
                    "last_modified_date": v.get("lastModifiedDate"),
                })

        return jsonify(rows)

    @app.route("/healthz")
    def healthz():
        return "ok\n"

    if __name__ == "__main__":
        app.run(host="0.0.0.0", port=9105)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trivy-cve-exporter
  namespace: ahmad-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trivy-cve-exporter
  template:
    metadata:
      labels:
        app: trivy-cve-exporter
    spec:
      serviceAccountName: trivy-cve-exporter
      containers:
        - name: exporter
          image: python:3.12-slim
          ports:
            - containerPort: 9105
              name: metrics
          command: ["/bin/sh", "-c"]
          args:
            - |
              pip install --no-cache-dir flask prometheus-client kubernetes && \
              python /app/exporter.py
          volumeMounts:
            - name: code
              mountPath: /app
      volumes:
        - name: code
          configMap:
            name: trivy-cve-exporter
---
apiVersion: v1
kind: Service
metadata:
  name: trivy-cve-exporter
  namespace: ahmad-monitoring
spec:
  selector:
    app: trivy-cve-exporter
  ports:
    - name: metrics
      port: 9105
      targetPort: 9105
