apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: host-vuln-scan
  namespace: ahmad-monitoring
spec:
  selector:
    matchLabels:
      app: host-vuln-scan
  template:
    metadata:
      labels:
        app: host-vuln-scan
    spec:
      automountServiceAccountToken: false

      containers:
        # =====================================================
        # 1️⃣ Trivy host scanner
        # =====================================================
        - name: trivy-host-scan
          image: aquasec/trivy:latest

          securityContext:
            runAsUser: 0
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false

          env:
            - name: TRIVY_CACHE_DIR
              value: /tmp/trivy-cache

          command: ["/bin/sh", "-lc"]
          args:
            - |
              set -e

              mkdir -p /data

              while true; do
                echo "[INFO] Running Trivy host scan..."

                # JSON output (Grafana / automation)
                trivy fs /host \
                  --scanners vuln \
                  --severity CRITICAL,HIGH,MEDIUM,LOW \
                  --skip-dirs /host/proc,/host/sys,/host/run,/host/dev \
                  --skip-dirs /host/var/lib/kubelet,/host/var/lib/containerd,/host/var/lib/docker \
                  --format json \
                  --output /data/host-scan.json || true

                # Table output (human readable)
                trivy fs /host \
                  --scanners vuln \
                  --severity CRITICAL,HIGH,MEDIUM,LOW \
                  --skip-dirs /host/proc,/host/sys,/host/run,/host/dev \
                  --skip-dirs /host/var/lib/kubelet,/host/var/lib/containerd,/host/var/lib/docker \
                  --format table \
                  --output /data/host-scan.txt || true

                # Extract metrics for Prometheus
                CRIT=$(grep -o '"Severity": "CRITICAL"' /data/host-scan.json | wc -l || true)
                HIGH=$(grep -o '"Severity": "HIGH"'     /data/host-scan.json | wc -l || true)
                MED=$(grep -o '"Severity": "MEDIUM"'   /data/host-scan.json | wc -l || true)
                LOW=$(grep -o '"Severity": "LOW"'      /data/host-scan.json | wc -l || true)

                printf 'trivy_host_vulnerabilities_total{severity="CRITICAL"} %s\n' "$CRIT"  >  /textfile/trivy_host_vulns.prom
                printf 'trivy_host_vulnerabilities_total{severity="HIGH"} %s\n'     "$HIGH" >> /textfile/trivy_host_vulns.prom
                printf 'trivy_host_vulnerabilities_total{severity="MEDIUM"} %s\n'   "$MED"  >> /textfile/trivy_host_vulns.prom
                printf 'trivy_host_vulnerabilities_total{severity="LOW"} %s\n'      "$LOW"  >> /textfile/trivy_host_vulns.prom

                echo "[INFO] Scan finished. Sleeping 6h..."
                sleep 21600
              done

          volumeMounts:
            - name: host-root
              mountPath: /host
              readOnly: true

            - name: trivy-data
              mountPath: /data

            - name: textfile
              mountPath: /textfile

            - name: tmp
              mountPath: /tmp

        # =====================================================
        # 2️⃣ nginx – exposes JSON over HTTP
        # =====================================================
        - name: trivy-http
          image: nginx:alpine
          ports:
            - containerPort: 8080
          command:
            - sh
            - -c
            - |
              sed -i 's/listen\s\+80;/listen 8080;/' /etc/nginx/conf.d/default.conf
              nginx -g 'daemon off;'
          volumeMounts:
            - name: trivy-data
              mountPath: /usr/share/nginx/html

      volumes:
        - name: host-root
          hostPath:
            path: /

        - name: trivy-data
          emptyDir: {}

        - name: textfile
          hostPath:
            path: /var/lib/node_exporter/textfile_collector
            type: DirectoryOrCreate

        - name: tmp
          emptyDir: {}
